
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-broker-1:
    image: confluentinc/cp-kafka:7.7.2
    container_name: kafka-broker-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /var/lib/kafka-1/data

  kafka-broker-2:
    image: confluentinc/cp-kafka:7.7.2
    container_name: kafka-broker-2
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /var/lib/kafka-2/data

  kafka-producer:
    build:
      context: ./ingestion
      dockerfile: Dockerfile
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
    environment:
      BOOTSTRAP_SERVERS: kafka-broker-1:9092,kafka-broker-2:9093

  spark-master:
    image: bitnami/spark:3.5.3
    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
    ports:
      - "7077:7077"
      - "8080:8080"

  spark-worker:
    image: bitnami/spark:3.5.3
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      BOOTSTRAP_SERVERS: kafka-broker-1:9092,kafka-broker-2:9093
    depends_on:
      - spark-master
      - kafka-broker-1
      - kafka-broker-2

  spark-app:
    build:
      context: ./processing
      dockerfile: Dockerfile
    depends_on:
      - spark-master
      - kafka-broker-1
      - kafka-broker-2
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
      BOOTSTRAP_SERVERS: kafka-broker-1:9092,kafka-broker-2:9093

  mariadb:
    image: mariadb:11.7.1-ubi9-rc
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: logs
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql  # Persistent Volume für MariaDB-Daten

  grafana:
    image: grafana/grafana:11.3.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards.yaml
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - mariadb
       


volumes:
  mariadb-data:  # Volume für MariaDB
    driver: local
  grafana-data:  # Volume für Grafana
    driver: local